<a href="https://colab.research.google.com/github/bcoelho92/Colgoogle/blob/main/Numpy_Gama.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Instalação

In [ ]:
#!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#Importação

In [ ]:
import numpy
numpy

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

# Lista vs Numpy

In [ ]:
lista = [1,2,3,4,5]
array = numpy.array([1,2,3,4,5])
type(lista), type(array)

(list, numpy.ndarray)

In [ ]:
lista = list(range(1000))
array = numpy.array(lista, dtype=int)

In [ ]:
import sys
sys.getsizeof(lista)

9120

In [ ]:
sys.getsizeof(array)

8104

In [ ]:
array.ndim

1

In [ ]:
len(lista)

5

In [ ]:
semestre = [[10,6,4,8], [5,6,5,6], [3,6,7,9]]
s_array = numpy.array(semestre)

In [ ]:
semestre

[[10, 6, 4, 8], [5, 6, 5, 6], [3, 6, 7, 9]]

In [ ]:
s_array

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6],
       [ 3,  6,  7,  9]])

In [ ]:
#s_array[0][0] = 'matheus'
semestre[0][0] = 10
semestre

[[10, 6, 4, 8], [5, 6, 5, 6], [3, 6, 7, 9]]

# Básico Numpy

In [ ]:
s_array.dtype

dtype('int64')

In [ ]:
s_array.ndim

2

In [ ]:
s_array+2

array([[12,  8,  6, 10],
       [ 7,  8,  7,  8],
       [ 5,  8,  9, 11]])

In [ ]:
s_array-2

array([[8, 4, 2, 6],
       [3, 4, 3, 4],
       [1, 4, 5, 7]])

In [ ]:
s_array/2

array([[5. , 3. , 2. , 4. ],
       [2.5, 3. , 2.5, 3. ],
       [1.5, 3. , 3.5, 4.5]])

In [ ]:
s_array * 2

array([[20, 12,  8, 16],
       [10, 12, 10, 12],
       [ 6, 12, 14, 18]])

In [ ]:
s_array % 2 == 0

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [ ]:
s_array

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6],
       [ 3,  6,  7,  9]])

In [ ]:
apoio = semestre.copy()
for notas in range(len(semestre)):
  for nota in range(len(semestre[notas])):
    apoio[notas][nota] = semestre[notas][nota] % 2 == 0

apoio

[[True, True, True, True],
 [False, True, False, True],
 [False, True, False, False]]

In [ ]:
s_array % 2 == 0

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [ ]:
s_array

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6],
       [ 3,  6,  7,  9]])

In [ ]:
s_array[1, [0,1,-1]].tolist()

[5, 6, 6]

In [ ]:
semestre[1][0:2] + [semestre[1][3]]

[5, 6, 6]

In [ ]:
s_array.astype(float)

array([[10.,  6.,  4.,  8.],
       [ 5.,  6.,  5.,  6.],
       [ 3.,  6.,  7.,  9.]])

# Criação de Arrays

In [ ]:
import numpy as np
#numpy.array
np.zeros([2, 3, 4])#2x3x4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones([2, 3, 4])#2x3x4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.full([2, 3, 4], 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [ ]:
notas = np.random.randint(low=0, high=11, size=[2, 3, 4])
notas

array([[[ 9,  1,  4,  9],
        [ 1,  1, 10,  5],
        [10,  2,  0,  2]],

       [[ 0, 10,  1,  5],
        [ 5,  4, 10,  0],
        [ 9, 10,  2,  7]]])

In [ ]:
np.full_like(notas, 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [ ]:
np.arange(start=0, stop=24).reshape([2,3,4]) 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
2*3*4, notas.size

(24, 24)

In [ ]:
exemplo = np.zeros([2,3,4]) #[arquivo, planilha, linha, coluna]
exemplo[1] = 1
exemplo

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
exemplo

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.random.rand(2,2) # numeros aleatórios entre [0, 1)

array([[0.27134551, 0.6901415 ],
       [0.61500327, 0.16311552]])

In [ ]:
# repete o array para alguma das dimensões
# lembrando que, se quiser repetir para baixo, o array tem que ter 2 dimensões
array = np.array([[0., 0., 0., 0.], [1,1,1,1]])
array
np.repeat(array, 4, axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.repeat(array, 2, axis=1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

# Seleção e Máscaras

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
#list(range(0, 36))
#list(range(36))
import numpy as np

'''
array = np.arange(0,36)
array = array.reshape([6,6])
array
'''

array = np.arange(0,36).reshape([6,6])
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
#[arquivo, planilha, linha, coluna]
#[linha, coluna]
# linha
array[2]
#array[2, :]

array([12, 13, 14, 15, 16, 17])

In [ ]:
#coluna
array[:, 2]

array([ 2,  8, 14, 20, 26, 32])

In [ ]:
#array[2:-1, 1:-2]
array[2:5, 1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [ ]:
array[:, [1,3,5]]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [ ]:
array[[0,2,4], :]
#array[::2,:]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
#[linha, coluna]
#[inicio:fim_nao_incluso:passo, inicio:fim_nao_incluso:passo]
array[1:5:2,:]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])